#!/bin/bash
# VitaminA launcher script

# Program files directory
# (Relative to the location from where
# this script is run.)
libdir=./lib

# Data files directory
# (Relative to the program files
# directory.)
datadir=../data

# Run the bot
cd $(dirname $(readlink -f $0))/$libdir
exec ./gawkldr -vdatadir="$datadir" -f core

