#!./gawkldr utils.awk
#
# VitaminA coin plugin
#
# Copyright Přemysl Janouch 2012. All rights reserved.
# See the file LICENSE for licensing information.
#
#

BEGIN \
{
	RS = "\r\n"
	ORS = RS

	print "privmsg"
	fflush("")
}

!initialized \
{
	srand()
	initialized = 1
}

{
	parse($0)
}

mcmd == "PRIVMSG" \
{
	mparam[1] = tolower(mparam[1])

	# Context = either channel or user nickname
	match(mwho, /^[^@!]+/)
	ctx = substr(mwho, RSTART, RLENGTH)
	if (mparam[0] ~ /^#/)
	{
		ctxquote = ctx ": "
		ctx = mparam[0]
	}
	else
		ctxquote = ""

	if (mparam[1] == "!coin")
	{
		if (int(2 * rand()) == 0)
			pmrespond("Heads.")
		else
			pmrespond("Tails.")
	}
	else if (mparam[1] ~ /^!dice/)
	{
		split(substr(mparam[1], \
			match(mparam[1], / |$/)), s, " ")

		choice = int(s[1])
		if (choice <= 0)
			pmrespond("Invalid or missing number.")
		else
			pmrespond(1 + int(choice * rand()))
	}
}

function pmrespond (text)
{
	print "PRIVMSG " ctx " :" ctxquote text
}

{
	print ""
	fflush("")
}

