#!/bin/sh
#
# VitaminA GAWK script loader
# Copyright Přemysl Janouch 2010. All rights reserved.
# See the file LICENSE for licensing information.
#
#

# The first parameter (which is #!./gawkldr <this one>)
# specifies gawk scripts to load before the main script.
# This list is separated by commas. gawk won't receive
# correct parameters if this parameter is missing.
scripts=`echo $1 | sed 's/,/\n-f\n/'`
shift
exec gawk -f $scripts -f $*

